### ISSUE TITLE
Bing asks for a different topic when using transcription.

### ISSUE THREAD

**Issue by Abdalnablse10** [WAppAI/assistant#216]
Simply saying hello would trigger it with transcription, but doesn't get triggered when jailbreak is enabled.

I use local transcription btw.

**Comment by Luisotee** [comment]
Try turning on the jailbreak with `!jailbreak on`. I think there might be a bug with the automatic activation of the jailbreak.

**Comment by Abdalnablse10** [comment]
Turning on the jailbreak does fix it.

**Comment by beshoo** [comment]
Is there a way to enable the jailbreak feature on all chats without having to manually send the command via chat? 

Also, the bot doesn't seem to be using the updated ASSISTANT_NAME in the .env file even though I changed it.

**Comment by choudhryfrompak** [comment]
hey Luisotee is there any way that we can enable jailbreak on all chats

**Comment by Luisotee** [comment]
@beshoo @choudhryfrompak I already intended for jailbreak to be on all the time, having it disabled by default is not a feature, its a bug. Next weak I should have some time to fix it

**Comment by Luisotee** [comment]
@beshoo @choudhryfrompak Should be fixed with #224
