### ISSUE TITLE
Without the bot being asked, it sends this message below in the groups

### ISSUE THREAD

**Issue by solution01** [WAppAI/assistant#220]
[Sydney Bot]: Too many unread messages (4) since I've last seen this chat. I'm ignoring them. If you need me to respond, please @mention me or quote my last completion in this chat.
![Screenshot_2023-11-01-09-16-29-40_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/WAppAI/assistant/assets/106486116/b268f86e-a78a-4d32-9e13-743e7a1bb903)

**Comment by Luisotee** [comment]
@solution01  This message should happen only after the bot is restarted to inform the user it will ignore the messages. Did you restart the bot before these messages or did it just send out of nowhere?

**Comment by solution01** [comment]
The message was sent out of nowhere.

**Comment by solution01** [comment]
I collected some pm2 logs for you to take a look at
![imagem_2023-11-01_120032974](https://github.com/WAppAI/assistant/assets/106486116/c628aadd-ec9f-4629-ae5c-a7a6ee4fc32c)

**Comment by Luisotee** [comment]
@solution01  That is all how it should work, what it shoudnt do is send more than one of the "Too many unread messages (4) since..." messages per chat when it restart. If it's than there is a problem.

I am gonna do something to give a option to disable this message in the .env to fix it temporarily

**Comment by solution01** [comment]
> That is all how it should work, what it shoudnt do is send more than one of the "Too many unread messages (4) since..." messages per chat when it restart. If it's than there is a problem.
> 
> I am gonna do something to give a option to disable this message in the .env to fix it temporarily

Ok @Luisotee I'll wait for you to create this solution, thank you :)

**Comment by Luisotee** [comment]
@solution01 I added the option in #222. A definite fix will only be out when I have time i.e.: Só Deus sabe

**Comment by Luisotee** [comment]
@solution01 tem que deixar como false

**Comment by solution01** [comment]
Done and it's functional, thanks for your help :)
