### ISSUE TITLE
.env REPLY_TRANSCRIPTION property error

### ISSUE THREAD

**Issue by ItzTej8** [WAppAI/assistant#227]
(node:1136) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ALLOWED_USERS not provided. The bot will work, but will answer to everyone.
Error: Invalid REPLY_TRANSCRIPTION="undefined" provided. Please check the REPLY_TRANSCRIPTION variable your .env file.
    at checkEnv (file:///C:/Users/HP/Desktop/assistant-2.0.1/src/helpers/utils.ts:67:19)

**Comment by Luisotee** [comment]
This is an error with your .env. Probably in the ALLOWED_USERS and REPLY_TRANSCRIPTION part. I would suggest you copy the .env.example files again and fill it again

**Comment by ItzTej8** [comment]
REPLY_TRANSCRIPTION doesn't exist in .env.example

**Comment by Luisotee** [comment]
@ItzTej8 Should be fixed with #228
