### ISSUE TITLE
Assistant use bing even after providing OPENROUTER_API_KEY

### ISSUE THREAD

**Issue by Abdalnablse10** [WAppAI/assistant#260]
First when running the bot: BING_COOKIES not provided. The bot will work, but you may soon need to solve captchas.

And the bot gives mixed responses from bing and openrouter in whatsapp.

**Comment by Luisotee** [comment]
To use a specific model you should use the `!change` command.

By default it should always use Bing, but I have seen it messing up sometimes, not sure why yet though.
