### ISSUE TITLE
Unable to add Sydney to any Group with the bot stating User XY tried to add the bot...but is not allowed

### ISSUE THREAD

**Issue by MikeBivins** [WAppAI/assistant#270]
The bot instantly leaves any group I try to add it to, occasionally writing "Sorry User XY, you're not allowed...".

I have not modified the ALLOWED_USERS/BLOCKED_USERS variables in the .env file, as they are still commented out. Since these variables are intended to control user messaging permissions, they should not be preventing the bot from being added to groups. 

Additionally, I have not found any other environment variable that appears to enable or disable the bot in groups.

**Comment by Luisotee** [comment]
@MikeBivins Yeah this is bugged, you can circumvent it by joining manually or adding the numbers in the `ALLOWED_USERS`

**Comment by Luisotee** [comment]
Should be fixed with #276
