### ISSUE TITLE
APIError: No media found

### ISSUE THREAD

**Issue by ElliotBadinger** [WAppAI/assistant#273]
Getting a `No media found` error from Openrouter when I use the google/gemini-pro-vision model to query an image. See pictures below(Also, kindly note that I have set payment for Openrouter and when I query the image using Bing it works): 
![image](https://github.com/WAppAI/assistant/assets/114085572/373f0e77-050d-4ee5-af12-f19fc3cc37aa)
![image](https://github.com/WAppAI/assistant/assets/114085572/718a1736-b2eb-45a2-9958-1bd9ad8b70aa)

**Comment by ElliotBadinger** [comment]
I used the `!change google/gemini-pro-vision` command to change the model

**Comment by Luisotee** [comment]
Currently no model from openrouter support images by our side, only bing.

**Comment by ElliotBadinger** [comment]
Ok, thanks for the assistance :)
