### ISSUE TITLE
Error: Evaluation failed: Error: wid error: invalid wid

### ISSUE THREAD

**Issue by ElliotBadinger** [WAppAI/assistant#275]
Got the error in the title while the bot was running idle (not being prompted). Although it has joined several groups and a community it did not unexpectedly terminate when a member of a group sent it a message that was not directed to it. Here's the error it printed:
![image](https://github.com/WAppAI/assistant/assets/114085572/79978e15-1ddc-4b67-8a98-7f2610a8ff82)

**Comment by ElliotBadinger** [comment]
The error seems to be triggered when I join groups. And additionally, the bot seems to leave as soon as it is added

**Comment by Luisotee** [comment]
Sorry for the late reply, it's a problem with `ALLOWED_USERS=""` in the .env, currently the "fix" is to add your number in the allowed users, add the bot and then leave it commented again

**Comment by Luisotee** [comment]
Should be fixed with #276
