### ISSUE TITLE
jailbreak sydney

### ISSUE THREAD

**Issue by ginegine04** [WAppAI/assistant#285]
Currently Sydney doesn't understand the context, she doesn't remember the questions she just asked and she doesn't remember the name of the bot she set, the jailbreak doesn't seem to work even if it's active. I take the cookies from Chrome but without accessing the bing account (Could it be that the jailbreak doesn't work because I'm not logged in?) Currently, to exceed the request limit I take the cookies with proxies and it works but the jailbreak doesn't. 
Thanks for the assistance.

**Comment by Luisotee** [comment]
Try use the `!jailbreak on` command on whatsapp

**Comment by ginegine04** [comment]
sure, using the !jailbreak command it is active, but it still doesn't remember the things just said or deny that it's called as set in the .env as if the jailbreak didn't work, everything else
works

**Comment by Luisotee** [comment]
Can you send me your .env in my email? I can't replicate this issue you are having.

**Comment by Luisotee** [comment]
Also, try to do the `pnpm build` again, then send any message in whatsapp and do the `!change 1` and `!jailbreak on` command

**Comment by ginegine04** [comment]
thanks for your assistance I was able to resolve the issue by reinstalling the directory several times
